### ISSUE TITLE
安装遇到错误

### ISSUE THREAD

**Issue by zhangshoug** [liudengfeng/czipline#1]
$ pip install -r ./etc/requirements_add.txt
.......................................
 return s.encode('ascii')
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 222-223: ordinal not in range(128)
    
    ----------------------------------------
  Rolling back uninstall of cswd
 return s.encode('ascii')
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 207-208: ordinal not in range(128)

**Comment by liudengfeng** [comment]
删除requirements_add.txt中的中文，再次安装

**Comment by zhangshoug** [comment]
还是不行，在网上搜了下：
导入模块codecs
import codecs
codecs专门用作编码转换.codecs官方文档

import codecs
...
#写入文件函数
 def save_to_file(list, filename):                                           
     with codecs.open(filename, 'a', encoding='utf-8') as f:                 
         f.writelines(list)    
$ vi ./src/cswd/setup.py
$ vi ./src/odo/setup.py
修改setup.py文件后再安装，还是不行，再打开setup.py,似乎修改保存不了.
